name: Laravel CI/CD

on:
  push:
    branches:
      - main

env:
  IMAGE_NAME: "agungnugrohoo/usernameadinusa-simple-social-media"

jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v4

      - name: Build Image
        run: docker build -t $IMAGE_NAME .

      - name: Login Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASS }}

      - name: Push Image
        run: docker push $IMAGE_NAME

  deploy:
    needs: build
    runs-on: self-hosted

    steps:
      - name: Stop container lama
        run: docker rm -f tailadmin || true

      - name: Run container
        run: |
          docker run -d \
          --name tailadmin \
          -p 8090:8090 \
          $IMAGE_NAME
